### PR TITLE
Rewrite of the code to make it follow Swift guidelines

### PR DESCRIPTION
**Pull request by Pyroh**
I got rid of the Objective-C API dependency.
I made it the _swift-way_. I don't think it's a good thing to extend all `NSObject` instances. It's better to make some sort of _new_ API and write dedicated objects to handle it.

This way I think it's clearer and more secure.

Ideally I'll rewrite it to be a Cocoa framework. I had to put some structs and classes into the same file, a framework would make it  easier to put each struct and class in its own file.

### CODE REVIEW

**Comment by samhann** [comment]
I have merged your pull request. Its much swift-ier. However we now no longer have the automatic deregistration of the timer when the owner is deallocated. That was the reason I had extended NSObject. 

If you set yourself as an associated object , whenever the owner is released  , you get released as well , provided noone is holding on to you.

The code is much cleaner now, but could we find a way to still make that possible ?

**Comment by samhann** [comment]
We could set a dummy object as an associated object on the owner. And when it gets deallocated we d get a call in the deinit of the dummy object ,from where we could call clearTimersForOwner .

**Comment by samhann** [comment]
I've pushed an implementation of the above idea to master. It will work only if the owner is a subclass of NSObject.

**Comment by Pyroh** [comment]
I don't think auto deallocation is a thing.
If you take a look at _cocoa bindings_ or `NSNotificationCenter`.
For each of these things you have to explicitly tell the framework: "I want to bind this of this to this of this" or "I want this to listen to this kind of notifications". For Every it's the same: "I want this thing to happen every once in a while and be tied to this object".

The first 2 seems that they are auto deallocated. They're not. We should explicitly state that an object's property isn't bound anymore BEFORE deallocating it. As for the notifications thing, you should tell the framework that an object is no longer a listener for any notification. Why would Every do it in a different way ?

You should argue that if you don't do any of these explicit things it still works. You're right. The framework simply unbound or remove for listener list if the receiver is nil when something happens. We can implement a similar mechanism but not support auto-deallocation since it will be a pain in the ass since one want to use pure-swift classes.

**Comment by samhann** [comment]
Hmmm , how about this then.

Let the timer manager store the owner as a weak var. Before calling the closure we check if the owner is nil. If he is , we invalidate. 

Wouldn't that work for both ?

NSNotificationCenter uses a similar technique in iOS 9

https://developer.apple.com/library/mac/releasenotes/Foundation/RN-Foundation/index.html#10_11NotificationCenter

I'll look into doing this.

**Pull request merged**
